# Generated by Django 5.1.4 on 2024-12-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('empleados_actuales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_receta', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('numero_habitacion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('todo_incluido', models.BooleanField(default=False)),
                ('ocupada', models.BooleanField(default=False)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('nacionalidad', models.CharField(max_length=255)),
                ('id_unico_huesped', models.BigIntegerField(unique=True)),
                ('repetidor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('alcohol', models.BooleanField()),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros_por_unidad', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionesEmpleadosBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion_activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.bares')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionesHuespedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('en_hotel', models.BooleanField(default=True)),
                ('pago_realizado', models.BooleanField(default=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.habitaciones')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('version', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cocktail')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEstancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.habitaciones')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=50)),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.ingredientes')),
            ],
        ),
    ]
