[build]
default = "backend"


[build.backend]
path = "Backend/Django_test"
install = "pip install --upgrade pip && pip install -r requirements.txt"
build = ""
start = "gunicorn tutorial.wsgi:application --log-file -"

[build.frontend]
path = "Frontend/hotel-gestion"
install = "npm install"
build = "npm run build"
start = "npx serve -s build"
