# Generated by Django 5.1.4 on 2024-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_asignacionesempleadosbar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenElementos',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('es_cocktail', models.BooleanField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenelementos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroOrdenes',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle_orden', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registroordenes',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='asignacionesempleadosbar',
            table='asignacionesempleadosbar',
        ),
        migrations.AlterModelTable(
            name='asignacioneshuespedes',
            table='asignacioneshuespedes',
        ),
        migrations.AlterModelTable(
            name='bares',
            table='bares',
        ),
        migrations.AlterModelTable(
            name='cocktail',
            table='cocktail',
        ),
        migrations.AlterModelTable(
            name='cocktailingredientes',
            table='cocktailingredientes',
        ),
        migrations.AlterModelTable(
            name='empleados',
            table='empleados',
        ),
        migrations.AlterModelTable(
            name='habitaciones',
            table='habitaciones',
        ),
        migrations.AlterModelTable(
            name='huesped',
            table='huesped',
        ),
        migrations.AlterModelTable(
            name='ingredientes',
            table='ingredientes',
        ),
        migrations.AlterModelTable(
            name='movimientosstock',
            table='movimientosstock',
        ),
        migrations.AlterModelTable(
            name='ordenes',
            table='ordenes',
        ),
        migrations.AlterModelTable(
            name='registroestancias',
            table='registroestancias',
        ),
        migrations.AlterModelTable(
            name='registromovimientos',
            table='registromovimientos',
        ),
    ]
