from django.urls import path
from .views import (IngredientesListView, CocktailListView, AsignacionesActivasView,
                    AsignacionesPorHabitacionView, CrearOrdenView, LoginView,
                    OrdenesActivasView, OrdenElementosView, BaresListView,
                    CrearOrdenElementoView, CrearOrdenView, CocktailIngredientesList,
                    OrdenesTodasView, UpdateIngredienteView, IngredienteDetailView,
                    CrearCocktailIngredientesView,UpdateCocktailIngredienteView,
                    CrearCocktailView, CrearIngredienteView, GenerarConsumosHistoricosView,
                    GenerarPrediccionesView, GenerarStockActualView, 
                    SubirConsumoHistoricoView, GenerarReporteReabastecimientoView,
                    GenerarReporteEstadisticoExcelView, HuespedesListView,
                    CrearHuespedView, CrearAsignacionView, CrearHabitacionView,
                    ActualizarPagoAsignacionView, CheckoutHuespedView,
                    HabitacionesDisponiblesView, AsignacionesHuespedesListView,
                    AsignacionActivaPorHuespedView, HuespedDetailView,
                    CambiarActividadOrdenView, OrdenesPorAsignacionView,
                    UpdateCocktailView, EmpleadoListCreateAPIView,
                    BarCreateAPIView, EliminarOrdenElementoView,
                    RegistrarMovimientoStockView,ActualizarTandaOrdenView,
                    CerrarOrdenesPorAsignacionView, CrearOrdenConElementosView,
                    AgregarElementoOrdenView, UpdateEmpleadoActivoView,
                    UpdateBarActivoView, UpdateHuespedActivoView,
                    RegistroOrdenesListView, RegistroMovimientosListView,
                    RegistroEstanciasListView)


urlpatterns = [
    path("asignaciones-activas/", AsignacionesActivasView.as_view(), name="asignaciones_activas"),
    path("ordenes-activas/", OrdenesActivasView.as_view(), name="ordenes_activas"),
    path("ordenes/<int:id_orden>/elementos/", OrdenElementosView.as_view(), name='elementos_por_orden'),
    path("bares/", BaresListView.as_view(), name="bares_list"),
    path("login/", LoginView.as_view(), name="empleado_login"),
    path("nueva-orden/", CrearOrdenView.as_view(), name="nueva_orden"),
    path("asignaciones-activas/<int:habitacion>/", AsignacionesPorHabitacionView.as_view(), name="asignaciones_por_habitacion"),
    path("ingredientes/", IngredientesListView.as_view(), name="ingredientes_list"),
    path("cocktails/", CocktailListView.as_view(), name="cocktails_list"),
    path("crear-orden/", CrearOrdenView.as_view(), name="crear_orden"),
    path("crear-orden-elemento/", CrearOrdenElementoView.as_view(), name="crear_orden_elemento"),  
    path("cocktail-ingredientes/<int:cocktail_id>/", CocktailIngredientesList.as_view()),
    path("ordenes-todas/", OrdenesTodasView.as_view(), name="ordenes_todas"),
    path("ingredientes/<int:ingrediente_id>/update/", UpdateIngredienteView.as_view(), name="update-ingrediente"),
    path("ingredientes/<int:pk>/", IngredienteDetailView.as_view(), name="ingrediente-detail"),
    path("cocktailingredientes/", CrearCocktailIngredientesView.as_view(), name='crear_cocktailingredientes'),
    path("cocktailingredientes/<int:pk>/", UpdateCocktailIngredienteView.as_view(), name='update_cocktail_ingrediente'),
    path("ingredientes/crear/", CrearIngredienteView.as_view(), name="crear_ingrediente"),
    path("cocktails/crear/", CrearCocktailView.as_view(), name="crear_cocktail"),
    path("reportes/consumos-historicos/", GenerarConsumosHistoricosView.as_view(), name="reportes_consumos_historicos"),
    path("reportes/predicciones/", GenerarPrediccionesView.as_view(), name="reportes_predicciones"),
    path("reportes/stock-actual/", GenerarStockActualView.as_view(), name="reportes_stock_actual"),
    path("reportes/subir-consumo/", SubirConsumoHistoricoView.as_view(), name='subir_consumo'),
    path("reportes/reabastecimiento/", GenerarReporteReabastecimientoView.as_view(), name='reabastecimiento'),
    path("reportes/estadistico/", GenerarReporteEstadisticoExcelView.as_view(), name="generar_reporte_estadistico"),
    path("gestion/huespedes/", HuespedesListView.as_view(), name="huespedes_list"),
    path("huespedes/nuevo/", CrearHuespedView.as_view(), name="crear_huesped"),
    path("asignaciones/nueva/", CrearAsignacionView.as_view(), name="crear_asignacion"),
    path("habitaciones/nueva/", CrearHabitacionView.as_view(), name="crear_habitacion"),
    path("asignaciones/<int:id_asignacion>/pago/", ActualizarPagoAsignacionView.as_view(), name="actualizar_pago_asignacion"),
    path("asignaciones/<int:id_asignacion>/checkout/", CheckoutHuespedView.as_view(), name="checkout_huesped"),
    path("gestion/habitaciones/", HabitacionesDisponiblesView.as_view(), name="habitaciones_disponibles"),
    path("gestion/asignaciones/", AsignacionesHuespedesListView.as_view(), name="asignaciones_list"),
    path("gestion/huespedes/<int:id_huesped>/asignacion-activa/", AsignacionActivaPorHuespedView.as_view(), name='asignacion-activa-huesped'),
    path("gestion/huespedes/<int:id_huesped>/", HuespedDetailView.as_view(), name='huesped-detalle'),
    path("ordenes/cambiar-actividad/<int:pk>/", CambiarActividadOrdenView.as_view(), name='cambiar-actividad-orden'),
    path("ordenes/por-asignacion/<int:id_asignacion>/", OrdenesPorAsignacionView.as_view(), name='ordenes-por-asignacion'),
    path("cocktails/<int:id_cocktail>/", UpdateCocktailView.as_view(), name='update_cocktail'),
    path("empleados/", EmpleadoListCreateAPIView.as_view(), name="empleados_list"),
    path("empleados/nuevo/", EmpleadoListCreateAPIView.as_view(), name="crear_empleado"),
    path("bares/nuevo/", BarCreateAPIView.as_view(), name="crear_bar"),
    path("ingredientes/<int:ingrediente_id>/movimiento/", RegistrarMovimientoStockView.as_view(), name='registrar_movimiento_stock'),
    path("ordenes/<int:id_orden>/actualizar-tanda/", ActualizarTandaOrdenView.as_view(), name="actualizar_tanda_orden"),
    path("ordenes/por-asignacion-todo-incluido/<int:id_asignacion>/", CerrarOrdenesPorAsignacionView.as_view(), name='ordenes-por-asignacion-todo-incluido'),
    path("crear-orden-con-elementos/", CrearOrdenConElementosView.as_view(), name='crear-orden-con-elementos'),
    path("ordenes/<int:id_orden>/elementos/<int:id_elemento>/eliminar/", EliminarOrdenElementoView.as_view(), name='eliminar-elemento'),
    path("ordenes/<int:id_orden>/agregar-elemento/",AgregarElementoOrdenView.as_view(),name="agregar_elemento_orden"),
    path("empleados/<int:pk>/activo/", UpdateEmpleadoActivoView.as_view(), name='empleados-update-activo'), 
    path("bares/<int:pk>/activo/", UpdateBarActivoView.as_view(), name='bares-update-activo'),  
    path("huespedes/<int:pk>/activo/", UpdateHuespedActivoView.as_view(), name='huespedes-update-activo'),
    path("registroordenes/", RegistroOrdenesListView.as_view(), name='registroordenes-list'),
    path("registromovimientos/", RegistroMovimientosListView.as_view(), name='registromovimientos-list'),
    path("registroestancias/", RegistroEstanciasListView.as_view(), name='registroestancias-list'),
]