# Generated by Django 5.1.4 on 2024-12-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionesempleadosbar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='asignacioneshuespedes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bares',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cocktailingredientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='habitaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='huesped',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ingredientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movimientosstock',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ordenes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroestancias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registromovimientos',
            options={'managed': False},
        ),
    ]
