# Generated by Django 5.1.4 on 2024-12-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_ordenelementos_registroordenes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionesEmpleadosBar',
        ),
    ]
